# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: sidebar
  product: Askdata
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Overview
    output: web, pdf
    folderitems:

    - title: What is Askdata
      url: product/index
      output: web, pdf
      type: homepage

    - title: Why Askdata
      url: product/why-askdata
      output: web, pdf
      type: homepage

    - title: Video Overview
      url: product/video-overview
      output: web, pdf

  - title: Features
    output: web, pdf
    folderitems:

    - title: Search Insights
      url: product/search-insights
      output: web, pdf

    - title: Push Insights
      url: product/push-insights
      output: web, pdf

    - title: Data Personalization
      url: product/data-personalization
      output: web, pdf

    - title: Data Collaboration
      url: product/share-insights
      output: web, pdf

  - title: Apps
    output: web, pdf
    folderitems:

    - title: iOS App
      url: product/ios
      output: web, pdf

    - title: Android App
      url: product/android
      output: web, pdf

  - title: Messaging
    output: web, pdf
    folderitems:

    - title: Microsoft Teams
      url: product/msteams
      output: web, pdf

    - title: Slack
      url: product/slack
      output: web, pdf

  - title: Plugins
    output: web, pdf
    folderitems:

    - title: Google Chrome Extension
      url: product/google-chome-extension
      output: web, pdf

    - title: Excel
      url: product/excel
      output: web, pdf

    - title: Google Sheet
      url: product/gsheet
      output: web, pdf
